[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Quadrrl"
author = "Laban Njoroge Mahihu"
maintainer = "Laban Njoroge Mahihu"
description = "A benchmark suite for quadruped robot reinforcement learning built on NVIDIA Isaac Lab"
repository = "https://github.com/lbnmahs/quadrrl.git"
keywords = ["reinforcement-learning", "quadruped-robots", "isaac-lab", "robotics", "benchmark", "locomotion", "navigation", "marl"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "quadrrl"

[isaac_lab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"